source/index.html.md
Work in progress introduction to the GOV.UK Content API
=> Add introductory sections

source/index.html.md
https://trello.com/c/AaQa591M/1054-1-add-more-details-to-the-reference-documentation
A bit more info on details, metadata and the path parameter.
=> Add more reference details

source/technical.html.md
[Trello Card](https://trello.com/c/uKYlfGlx/1091-remove-sections-that-we-arent-writing)
=> Remove sections of the API we don't need

source/index.html.md
[Trello Card](https://trello.com/c/3piyXDrU/1070-write-about-the-govuk-content-api-section-of-api-documentation-1)
=> Improve the section about the API

source/technical.html.md
https://trello.com/c/61xiu0VX/1077-write-versioning-section-of-api-documentation-6
=> Add content to the versioning section

source/index.html.md
https://trello.com/c/vzsT6fUH/1074-write-quick-start-guide-and-examples-section-of-api-documentation-3
=> Rework quick start and examples section

source/technical.html.md
https://trello.com/c/OmEp7HaN/1069-write-authors-and-acknowledgments-section-of-api-documentation-9
=> Add to Authors and Acknowledgements section

source/technical.html.md
https://trello.com/c/5eWNwoa0/1075-write-security-and-compliance-section-of-api-documentation-8
**TODO**: Needs a real email address!
=> Add some security subtopics and text

templates/heading_main.dot
Handle multiple endpoints in a conditional, seems unlikely you'd have
multiple.
=> Add header before endpoint

generate.js
Seems to be overlooked in the code for Widdleshins so you have to take
this round the houses approach.
=> Include schema description in schema sections

source/404.html.md, source/layouts/core.erb
https://trello.com/c/eHXQUqR5/1094-add-a-404-page-for-the-documentation
=> Add custom 404 page

templates/heading_code_samples.dot, templates/heading_example_responses.dot, templates/heading_main.dot
Based on feedback from a developer who is not familiar with the Content API, we make some amendments to the current iteration of the documentation.
https://trello.com/c/tsv24HQ8/1068-05-documentation-improvements-based-on-initial-feedback
=> Documentation improvements

generate.js, templates/code_shell.dot, templates/heading_code_samples.dot, templates/heading_example_responses.dot
Fixes the broken code sample thing too.
=> Switch to using one shell example for code samples

config/tech-docs.yml, source/index.html.md, templates/heading_main.dot, templates/schema_header.dot
[Trello Card](https://trello.com/c/7XPMle03/1105-quickish-fixes-to-documentation)
=> Quick(ish) fixes

.template_version, config/tech-docs.yml, source/layouts/_analytics.erb
[Trello Card](https://trello.com/c/8uTDiHEq/1082-1-add-ga-tracking-to-api-documentation-page)
=> Add GA tracking code

source/index.html.md
https://trello.com/c/B62dFYcP/1106-content-fixes-for-documentation
Add Authentication section
Following feedback from Jen L, rearrange intro into can and can't sections.
=> Restructure about section

templates/heading_main.dot
Attempt to make this less of a random section.
=> Add prefix text before base url

source/index.html.md.erb
https://trello.com/c/XPAWbL4K/1081-05-add-beta-banner-to-the-api-documentation
=> Add feedback survey to Beta software section

config/tech-docs.yml, source/getting-started.html.md
Initial draft of content for this page.
=> Getting started page

source/index.html.md.erb
This fixes issues identified doing a link sweep.
=> Link review

source/index.html.md.erb
Mercifully few issues found
[Trello](https://trello.com/c/xpuBRAXD/1118-review-the-content-api-documentation-microsite)
=> Changes from Hongs review

source/getting-started.html.md, source/index.html.md.erb
For [Trello](https://trello.com/c/xpuBRAXD/1118-review-the-content-api-documentation-microsite)
=> Minor grammatical changes

source/index.html.md.erb
Before it was slightly confusing as it wasn't clear exactly what it means for content to be unmigrated and this provides a more detailed description.
=> Make it more clear about what unmigrated content may appear as

config/tech-docs.yml
It's not something we look at, and we don't have an appropriate cookie policy.
=> Remove GA tracking

source/getting-started.html.md, source/index.html.md.erb
See individual commits for more details.
[Trello Card](https://trello.com/c/9zYixzLx/2102-2-fix-accessibility-issues-in-content-api-docs)
=> Various accessibility improvements

config/tech-docs.yml, source/accessibility.html.md
This has been written for us by the tech writers and will show as a link in the footer.
Following on from #55 and #59
=> Add accessibility statement

source/accessibility.html.md
Update last reviewed date to December 2020
=> Update last reviewed date

source/accessibility.html.md
This updates the Accessibility Statement to reference issues with the Technical Documentation template. 
[Trello](https://trello.com/c/3R8fpiGF)
=> Update Accessibility Statement
